import { aiPath, requestPaths } from '../core/paths.js';
import { readJson, readText, writeText } from '../core/fs.js';
import { nowIso } from '../core/format.js';

export function generateComponentPlan(root, requestId, config = {}) {
  const intake = readJson(requestPaths(root, requestId).intake, null) || {};
  const approved = readJson(requestPaths(root, requestId).approvedDesign, null);
  const answers = readText(requestPaths(root, requestId).answersMd, '').trim();
  const framework = config.components?.default_framework || 'react';
  const components = inferComponents(intake, approved);
  const md = [
    `# Component Plan — ${requestId}`,
    '',
    `Generated at: ${nowIso()}`,
    `Framework: ${framework}`,
    `Work type: ${intake.work_type || 'unknown'}`,
    '',
    '## Components',
    '',
    ...components.map((c, i) => `${i + 1}. **${c.name}** — ${c.role}\n   - Priority: ${c.priority}\n   - Suggested path: ${c.path}\n   - Notes: ${c.notes}`),
    '',
    '## Shared rules',
    '',
    '- Prefer deep reusable modules over giant page files.',
    '- Keep placeholder data explicit until real content exists.',
    '- Map approved design regions to concrete components before coding.',
    '',
    '## User clarifications',
    '',
    answers || '- No additional user answers recorded.'
  ].join('\n');
  const file = aiPath(root, 'designs', 'components', `${requestId}-component-plan.md`);
  writeText(file, md);
  return { request_id: requestId, path: file, markdown: md, components };
}

function inferComponents(intake, approved) {
  const ask = String(intake.raw_user_ask || '').toLowerCase();
  const components = [];
  if (/landing|home|homepage|hero/.test(ask)) components.push(base('HeroSection', 'Primary value proposition and CTA above the fold', 'high'));
  if (/servic/.test(ask)) components.push(base('ServicesSection', 'Service cards or service list', 'high'));
  if (/before|after|galer|portfolio/.test(ask)) components.push(base('BeforeAfterGallery', 'Comparison/gallery section', 'high'));
  if (/cta|contact|whatsapp|email|phone/.test(ask) || intake.work_type === 'frontend_visual') components.push(base('ContactCTA', 'Conversion section with explicit placeholders if needed', 'high'));
  components.push(base('Footer', 'Professional footer with honest contact placeholders', 'medium'));
  if (approved) components.unshift(base('ApprovedDesignFrame', `Implementation anchor for ${approved.approved_design}`, 'high', 'src/design/approved-frame.ts'));
  if (!components.length) components.push(base('FeatureShell', 'Core shell inferred from request', 'medium'));
  return components;
}

function base(name, role, priority, p = null) {
  return { name, role, priority, path: p || `src/components/${name}.tsx`, notes: 'Generated by component planner.' };
}
